export const config = {
  TUTOR_FEE_PER_SESSION: 100,
  DEMO_CLASS_FEE: 99,
  BACKEND_URL: process.env.REACT_APP_BACKEND_URL,
  VIDEOSDK_TOKEN: process.env.REACT_APP_VIDEOSDK_TOKEN,
  RECORDING_API: "https://api.videosdk.live/v2/recordings",

  CANCEL_SESSION_COUNT: process.env.CANCEL_SESSION_COUNT || 2,
  CANCEL_DEMO_SESSION_COUNT: process.env.CANCEL_DEMO_SESSION_COUNT || 1,
  SESSION_DURATION: process.env.SESSION_DURATION || 28,
  SHOW_AVAILABLE_SLOTS_BEFORE: 60, // 60 minutes
  CANCEL_SESSION_DURATION_IN_HRS: 2, // BEFORE 2 HRS
  EDIT_SESSION_DURATION_IN_HRS: 1, // BEFORE 2 HRS
};
